"""Tiny local-dev-only `.env` loader — populates the real process
environment, unlike pydantic-settings' own `env_file` support (removed
from every service's `Settings`) which only ever populated that one
`Settings` instance and left libraries that read env vars directly
(e.g. boto3's native `AWS_ENDPOINT_URL` support) unaware of the values.

Deliberately not a new `python-dotenv` dependency: every `.env.local`
here is generated by `bootstrap.py` itself in a simple `KEY=value`
format, so a full parser (quoting, multiline values, interpolation)
buys nothing.
"""

import os
from pathlib import Path


def load_env_file(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        # setdefault: a real env var already set in the process always
        # wins over the file, same precedence pydantic-settings' env_file
        # used to have relative to real env vars.
        os.environ.setdefault(key.strip(), value.strip())
